### ISSUE TITLE
Поддержка прокси

### ISSUE THREAD

**Issue by crinny** [crinny/zoomrip#11]

**Comment by nm17** [comment]
У trio-websocket и trio-websockets нету поддержки прокси, и патчить socks не получится.
Но если кто-то сможет сделать, будет круто.

**Comment by mishailovic** [comment]
Если прокси нужен только для обхода бана по ip можно использовать torsocks, если не ошибаюсь он каждый раз берет разные ip.

**Comment by crinny** [comment]
Можно установить прокси для всего скрипта (не уверен, что работает):
```python
import socket
import socks

socks.set_default_proxy(socks.SOCKS5, "localhost", 9150)
socket.socket = socks.socksocket
```

**Comment by mishailovic** [comment]
Выбор же у юзера будет, юзать прокси или нет?

**Comment by crinny** [comment]
> Выбор же у юзера будет, юзать прокси или нет?

Да

**Comment by nm17** [comment]
> Можно установить прокси для всего скрипта (не уверен, что работает):
> 
> ```python
> import socket
> import socks
> 
> socks.set_default_proxy(socks.SOCKS5, "localhost", 9150)
> socket.socket = socks.socksocket
> ```

Эмм, не знаю как, но теперь это работает с трио. Хз почему до этого не работало.
Скоро кину пулл.
